# .pages.yml

# The base URL for your site
base_url: "https://example.com"

# Site title and description
title: "Your Site Title"
description: "A brief description of your site"

# Navigation configuration
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Posts"
    url: "/posts/"

# Sidebar configuration (if using a sidebar layout)
sidebar:
  - title: "Recent Posts"
    type: "recent_posts"
  - title: "Categories"
    type: "categories"

# Configure page-specific options
pages:
  - path: "index.md"
    layout: "home"
  - path: "about.md"
    layout: "page"
  - path: "_posts"
    layout: "post"

# Define the theme used for the site
theme: "minima"

# Metadata for individual pages or posts can be specified here
metadata:
  home:
    title: "Welcome to My Site"
  about:
    title: "About Us"
