title: Home

description: >
  BLog post for things i want to find later, like a public clipboard 
  
header_pages:
  - about.md

remote_theme: no-style-please

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-sitemap

minima:
 skin: auto

 
  
baseurl: ""
