title: Home
  
baseurl: ""


paginate: 5
paginate_path: "/page:num/"

markdown: kramdown
kramdown:
  input: GFM


defaults:
  - scope:
      path: "_posts"  
    values:
      layout: "post"
      
  
