author:
  name: kailash
  email: xkailashxx@gmail.com
description: >
  BLog post for things i want to find later, like a public clipboard 
  
#theme: minima for old version
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

header_pages:
  - about.md

minima:
 skin: auto

markdown: GFM
